Raise minimum tested compiler to rust 1.88
    error: rustc 1.87.0 is not supported by the following package:
      image@0.25.10 requires rustc 1.88.0
    Either upgrade rustc or select compatible dependency versions with
    `cargo update <name>@<current-ver> --precise <compatible-ver>`
    where `<compatible-ver>` is the latest version supporting rustc 1.87.0