Raise minimum tested compiler to 1.60
On older versions:

    error: failed to select a version for the requirement `image = "^0.25"`
    candidate versions found which didn't match: 0.24.5, 0.24.4, 0.24.3, ...
    location searched: crates.io index
    required by package `colorous v1.0.12`