Raise minimum tested compiler to rust 1.87
Required by zune-jpeg 0.5.7.

    error[E0133]: call to unsafe function `std::arch::x86_64::_mm256_set1_epi16` is unsafe and requires unsafe function or block
      --> $CARGO_HOME/registry/src/index.crates.io-1949cf8c6b5b557f/zune-jpeg-0.5.7/src/upsampler/avx2.rs:36:19
       |
    36 |     let v_three = _mm256_set1_epi16(3);
       |                   ^^^^^^^^^^^^^^^^^^^^ call to unsafe function
       |
       = note: consult the function's documentation for information on how to avoid undefined behavior